# Generated by Django 5.1 on 2024-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_reciever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reciever',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciever_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
