# Generated by Django 5.1 on 2024-09-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_reciever_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever_account',
            new_name='receiver_account',
        ),
    ]
