# Generated by Django 5.1 on 2024-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_reciever_account_transaction_receiver_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
